# Generated by Django 6.0.6 on 2026-08-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_major"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="mj_code",
        ),
    ]
