# Generated by Django 6.0.6 on 2026-08-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_remove_major_mj_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mj_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.major"
            ),
        ),
    ]
