# Generated by Django 6.0.6 on 2026-08-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_student_mj_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="หมวดหมู่")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_code",
                    models.CharField(max_length=20, unique=True, verbose_name="รหัสวิชา"),
                ),
                ("sub_name", models.CharField(max_length=200, verbose_name="ชื่อวิชา")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
        ),
    ]
